name: CDK Pipeline

on:
  push:
    branches:
      - gh-actions

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Synthesis
        run: cdk synth --output=./cdk.out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Deploy
        run: cdk deploy --all --verbose
