name: CDK Pipeline

on:
  push:
    branches:
      - gh-actions

jobs:
  synth:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Synthesis
        run: cdk synth --output=./cdk.out

      - name: CDK Deploy
        run: cdk deploy --all --verbose

      - name: Test
        run: ./test.sh
